from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.core.database import Base

class Thread(Base):
    __tablename__ = "threads"

    # We use a String ID here because thread IDs are usually UUIDs generated by the frontend or LangGraph
    id = Column(String, primary_key=True, index=True)
    
    # CRITICAL MULTI-TENANCY FIX: Link the thread to a specific user
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # NEW: Link to a Project (CASCADE wipes the chat if the project folder is deleted)
    project_id = Column(String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=True, index=True)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Establish relationships
    messages = relationship("Message", back_populates="thread", cascade="all, delete-orphan")
    project = relationship("Project", back_populates="threads")

class Message(Base):
    __tablename__ = "messages"

    id = Column(Integer, primary_key=True, index=True)
    thread_id = Column(String, ForeignKey("threads.id", ondelete="CASCADE"), nullable=False, index=True)
    role = Column(String, nullable=False) # Will store 'user', 'ai', or 'system'
    content = Column(Text, nullable=False) # Text instead of String for long Markdown responses
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    thread = relationship("Thread", back_populates="messages")